# Generated by Django 5.0.4 on 2025-02-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonio_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='testimonios/'),
        ),
    ]
